//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: ishape.cpp
//  Source: ishape.idl
//  Generated: Fri Mar 24 02:03:16 2017
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************

#include "ishape.h"




