//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: HelloWorldData.cpp
//  Source: ../../idl/HelloWorldData.idl
//  Generated: Tue Mar 28 13:02:27 2017
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************

#include "HelloWorldData.h"




